### ISSUE TITLE
how to use it?

### ISSUE THREAD

**Issue by sangthian** [Flamenco/intellivue#1]
doc is not clear to say how to use it

**Comment by Flamenco** [comment]
Hello @Jmx5200,
Have you visited the website at https://www.twelvetone.tv/docs/developer-tools/intellij-plugins/intellivue?

**Comment by Flamenco** [comment]
The main plugin function is to open a context popup over an item in your template, and then select `Goto/Create Vue Implementation`.  You are then guided through.  These actions are also added to the main menus.

There is also an `Analysis Tool Window` that you can open.

**Comment by sangthian** [comment]
thanks for replying,  maybe it's hard to open the popup in webstorm vue project , I tried the shortcut `shift-meta-alt-v`(alt? meta?) in mac and win laptop, but failed. And in keymap setting I cannot find anything about this plugin.

![Uploading Snipaste_2019-03-14_09-17-30.jpg…]()

**Comment by Flamenco** [comment]
First off, you need to have a Single File Component open (.sfc).  Next, you put the cursor on an item in your template, such as `<div>{{cursorOnMe}}</div>`.  Open a context menu (right click), or look in the main menu under  `code` or `refactor`.  After you try those actions, you can assign them to keyboard shortcuts in `preferences` by searching for the names.

**Comment by Flamenco** [comment]
@Jmx5200 Please let me know if the last post helped, and if I can close this issue.  Thanks!

**Comment by sangthian** [comment]
Thanks for replying, it's very helpful.
