### ISSUE TITLE
Button Text is scrambled in Rider 2020.2 EAP3

### ISSUE THREAD

**Issue by fergusmeiklejohn** [Flamenco/intellivue#11]
<img width="241" alt="Screenshot 2020-06-23 at 10 24 41" src="https://user-images.githubusercontent.com/11864025/85353992-17316600-b53c-11ea-88dd-1c16068413f4.png">
<img width="146" alt="Screenshot 2020-06-23 at 10 24 57" src="https://user-images.githubusercontent.com/11864025/85353995-1993c000-b53c-11ea-9ab1-ce6dbe86a101.png">

**Comment by Flamenco** [comment]
Hi @fergusmeiklejohn.

Thanks for the report.  Can you please post a sample minimal .vue file that reproduces the issue?

**Comment by fergusmeiklejohn** [comment]
I created a new project with latest version of Vue Cli: https://github.com/fergusmeiklejohn/inttest
I tested with Rider 2020.2 EAP and the bug was reproduced
I tested with Webstorm 2020.2 EAP and the bug was NOT reproduced.

Conclusion: bug is associated with Rider 2020.2 EAP

**Comment by Flamenco** [comment]
@fergusmeiklejohn So I will close this and you can reopen after final version is released if you still encounter problems.

FYI, behind the scenes, Jetbrains is removing support for the browser widget supplied by JavaFX and using Chromium instead.  This should double the speed!  But there will be issues at first...
