### ISSUE TITLE
automatic alphabatization of properties: how to turn it off?

### ISSUE THREAD

**Issue by smilingkite** [Flamenco/intellivue#12]
Hi,

Hopefully there is a setting I'm just not finding (the docs do suggest this). 

I'm using webstorm and when I let it reformat vue-files automatically (in bulk), it will alphabetize the props on components. This is annoying and causes merge-conflicts. It doesn't happen on individual files, thankfully. 

So how do I turn this off?

**Comment by Flamenco** [comment]
Hi @smilingkite please help me understand your issue better.  Are you are choosing to 'sort', or is that happening automatically?  Are you selecting multiple files, then sorting from the main menu?.  If so, can you post a sample of what it is doing, and what the expected behavior should be?

**Comment by smilingkite** [comment]
Thanks for responding.

I was selecting multiple files and then automatically having webstorm clean up my code. 

It turns out that in the popup that follows (before code clean up), I should have unselected most of the options. 

Now I can clean my code without automatic sorting.
