### ISSUE TITLE
IntelliVue is incompatible with WebStorm (2021.2) build #WS-212.4746.80, built on July 23, 2021

### ISSUE THREAD

**Issue by sunmachine** [Flamenco/intellivue#16]
IntelliVue 1.1.5 is incompatible with WebStorm (2021.2) build #WS-212.4746.80, built on July 23, 2021.

The current IntelliVue release requires IDE build 211.* or older.

<img width="551" alt="Screen Shot 2021-07-29 at 12 22 37" src="https://user-images.githubusercontent.com/2231775/127529107-df95648f-7bc6-4f49-8345-5b337b361d76.png">

**Comment by Flamenco** [comment]
Hello @sunmachine 
It is incompatible because we marked it a such.  Version 2021.2 has some issues we are working with JetBrains to resolve before releasing.  Should not be too long.

**Comment by sunmachine** [comment]
Thanks for the follow-up. Never touched the Jetbrains plugin dev ecosystem so I figured I would post the issue just in case it's not an obvious chain of communication.

Take it easy!

**Comment by Flamenco** [comment]
Fixed in release 1.1.6.  It may take a day or two for Jetbrains to publish, so I added the JAR to the release page for the impatient.

https://github.com/Flamenco/intellivue/releases
