### ISSUE TITLE
Plugin still broken for PhpStorm 2021.2

### ISSUE THREAD

**Issue by Terrijoo** [Flamenco/intellivue#17]
First of all, great plugin, been using it for quite some time and really happy about it. Keep up the good work!

On the new PhpStorm 2021.2 release, this plugin is still broken.
In PhpStorm itself, I can't update the plugin at all and adding the plugin manually through the latest release, I get this error:
![image](https://user-images.githubusercontent.com/5391946/127874032-6db1a1e9-5f70-4d2a-af31-273eb02d4f65.png)

On the Jetbrains Plugin page, it even states, that this plugin is incompatible:
![image](https://user-images.githubusercontent.com/5391946/127874097-95a5e714-07e3-4fea-be6c-5d00e20eb3a6.png)

I've used the 1.1.6 release from here:
https://github.com/Flamenco/intellivue/releases

Anything I am just missing?

**Comment by Flamenco** [comment]
That dependency worked its way in for the current release after we started using Gradle to build it.

@Terrijoo I can remove the dependency it and post a draft without,  if you want to try it.

**Comment by Flamenco** [comment]
https://github.com/Flamenco/intellivue/releases/tag/1.1.7

**Comment by Flamenco** [comment]
Seems to install fine without the dependency, so we just published 1.1.7 to marketplace.  Might take a couple of days to show up there.

**Comment by Flamenco** [comment]
Jetbrains fast-tracked the update.
https://plugins.jetbrains.com/plugin/12014-intellivue/versions
@Terrijoo I am closing issue.  Please confirm it works.  Thanks!

**Comment by Terrijoo** [comment]
Yes, it worked!
Thanks a lot for the fast support and keep up the good work! 🙂
