### ISSUE TITLE
Cant get this to work in latest phpstorm

### ISSUE THREAD

**Issue by msacchetti** [Flamenco/intellivue#2]
I installed this in the latest PHPstorm, on a clean vue project created from the vue-cli.

There is no way to use this, no actions, or anything in the code menu in single file components.

**Comment by Flamenco** [comment]
@msacchetti , so to confirm, you installed both the Vue plugin and the IntelliVue plugin.  Then opened up a single file component, and the code menu **does not** have these items at the bottom:

<img width="300" alt="Screen Shot 2019-04-10 at 7 41 39 AM" src="https://user-images.githubusercontent.com/819940/55875864-20672a80-5b64-11e9-8b65-40e26c3aab8a.png">

Are there any errors reported in your log?  Also, did this ever work for you?

**Comment by msacchetti** [comment]
I have not tried to use this before.

1) updated Vue plugin for PHPstorm 2019.1
2) installed intellivue and restarted
3) created a brand new, clean Vue project from the vue CLI and made some single file components
4) In a single file component, there are no options in the code menu
5) When i "search everywhere" by double tapping shift, if i type in intellivue, i see it under "Actions" and the switch is turned OFF, even though the plugin is active. When i switch it on, it makes me restart PHPstorm - and then when it starts back up, the Action is turned off in that menu even though the plugin is on.

I have not checked error logs but i can maybe do that this week.

**Comment by gisu** [comment]
Same here, PHPStrom 2019.1. A new fresh plugin install but the Plugin wont activate.

![image](https://user-images.githubusercontent.com/442468/56418755-2e215c00-6298-11e9-869f-eef7195957e0.png)

**Comment by Flamenco** [comment]
@gisu Do you have any information from the IJ logs?  I am thinking there is a dependency that is not getting installed.

**Comment by entioentio** [comment]
I can't enable intelliVue in latest phpstorm either
![image](https://user-images.githubusercontent.com/10046841/56664620-b6449e80-66a8-11e9-98e0-8429145def10.png)

Excerpt from IJ logs:
```019-04-24 15:41:01,120 [   6381]   INFO - llij.ide.plugins.PluginManager - Plugin 'IntelliVue' can't be loaded because: Plugin does not include any module dependency tags in its plugin.xml therefore is assumed legacy and can be loaded only in IntelliJ IDEA```

**Comment by Manyaka** [comment]
Same with the WebStorm 2019.1
<img width="1225" alt="Screenshot 2019-05-02 at 07 00 58" src="https://user-images.githubusercontent.com/6417966/57056051-8b5dda00-6ca8-11e9-8d7d-3a56028cad2b.png">
<img width="878" alt="Screenshot 2019-05-02 at 07 02 45" src="https://user-images.githubusercontent.com/6417966/57056063-a16b9a80-6ca8-11e9-97be-a00292ecd1cc.png">

**Comment by Flamenco** [comment]
We installed a fresh copy of PHP storm and found this in our logs:

> 2019-05-03 09:02:32,568 [   3284]   INFO - llij.ide.plugins.PluginManager - Plugin 'IntelliVue' can't be loaded because: Plugin does not include any module dependency tags in its plugin.xml therefore is assumed legacy and can be loaded only in IntelliJ IDEA 

We will add dependency information into 1.0.0-rc.5 and update ASAP.

**Comment by Flamenco** [comment]
1.0.0-rc.5 has been confirmed to resolve this issue and submitted to JetBrains.  It usually takes a couple of days for JB to approve.

Thank you all for your feedback!
