### ISSUE TITLE
Add vuetify to list of links

### ISSUE THREAD

**Issue by kellerkind87** [Flamenco/intellivue#21]
It would be very nice, if there would be also a link to vutify documentation besides the router and vuex docs.

**Comment by Flamenco** [comment]
@kellerkind87  Yes! Vuetify and Quasar seem like good links.  The link list has not been working in latest builds though.  Are they working for you?  If so, what version of IJ are you using.

**Comment by kellerkind87** [comment]
![image](https://user-images.githubusercontent.com/49106042/164402815-2b96897c-91ab-40b0-bf10-ede77c90b6cd.png)
![image](https://user-images.githubusercontent.com/49106042/164403058-575db72e-01ae-4c85-9a95-cf2a5b8fda19.png)

Plugin Version: 1.1.12

hope those infos help

**Comment by Flamenco** [comment]
Is that Mac, PC, or Linux?

**Comment by kellerkind87** [comment]
PC - Windows 11

**Comment by Flamenco** [comment]
I just added vuetify and quasar to the list of links.  It currently only in the 2022.3.EAP release.

<img width="511" alt="Screen Shot 2022-09-30 at 10 18 36 PM" src="https://user-images.githubusercontent.com/819940/193379275-f72192af-9272-424e-aaac-95c20264ad7f.png">

<img width="512" alt="Screen Shot 2022-09-30 at 10 18 45 PM" src="https://user-images.githubusercontent.com/819940/193379276-6f82ad40-42ed-4db5-9bd8-286d2e385c6a.png">

<img width="506" alt="Screen Shot 2022-09-30 at 10 18 58 PM" src="https://user-images.githubusercontent.com/819940/193379277-407cc68a-5194-4b35-94c6-4477dd9fbab9.png">
