### ISSUE TITLE
IntelliVue is incompatible with WebStorm (2022.2) build #WS-222.3345.108, built on July 22, 2022

### ISSUE THREAD

**Issue by lucaspouchot** [Flamenco/intellivue#25]
IntelliVue 1.1.12 is incompatible with WebStorm (2022.2) build #WS-222.3345.108, built on July 22, 2022.

The current IntelliVue release requires IDE build 221.* or older.

![image](https://user-images.githubusercontent.com/55501335/181711825-143e91b1-5193-4ede-b440-305da81b7f77.png)

![image](https://user-images.githubusercontent.com/55501335/181711996-0decfd10-8c44-4879-be48-403bf1f55ab3.png)

**Comment by Flamenco** [comment]
Thank you for the report.  This has been updated in version 1.1.13

Jetbrains should push the new version though in the next couple of days.
