### ISSUE TITLE
IntelliVue is incompatible with 2023.3 EAP

### ISSUE THREAD

**Issue by Zae** [Flamenco/intellivue#28]
Is it possible to make the plugin compatible with the newest EAP?

**Comment by Flamenco** [comment]
Hello @Zae,

Yes, we can upload our in-house version ASAP.  We were testing some newer features hence the delay.

**Comment by Flamenco** [comment]
Updated with IntelliVue 1.1.44.

May take a day or two for Jetbrains to validate.
