### ISSUE TITLE
"Show Vue Analysis When Opening" option not there?

### ISSUE THREAD

**Issue by goela268** [Flamenco/intellivue#29]
In the docs, it says there is an option to Open the Analysis tool window whenever you open a Vue file:
https://www.twelvetone.tv/docs/developer-tools/intellij-plugins/intellivue#show-vue-analysis-when-opening

However, for me, I only have the option to open the Analysis window for the current file, see:
![image](https://github.com/Flamenco/intellivue/assets/67412191/4052b3b7-8a02-4846-9ea5-20682eedab11)

PhpStorm 2023.2.2
IntelliVue 1.1.41

What am I doing wrong?

**Comment by Flamenco** [comment]
It looks like this is a bug in the recent versions.

**Comment by Flamenco** [comment]
It is marked as an "experiment feature", so you will need to enable this in your plugin settings.

I will update the documentation to indicate that.
