### ISSUE TITLE
找不到intellivue工具栏

### ISSUE THREAD

**Issue by li-2021** [Flamenco/intellivue#30]
WebStorm 2023.3(#WS-233.11799.229)即使打开vue文件，也没有出现插件的工具栏

**Comment by Flamenco** [comment]
安装了什么版本的插件？

**Comment by li-2021** [comment]
1.1.46

**Comment by yebei199** [comment]
我也是,找不到

**Comment by Flamenco** [comment]
Version 1.2.4 was released today that should address this issue.  It may take a day or two for Jetbrains to  approve it.

今天发布的 1.2.4 版本应该可以解决这个问题。 Jetbrains 可能需要一两天的时间才能批准。

**Comment by Flamenco** [comment]
This was released.  Please let me know if issue is fixed so I can close this.

https://plugins.jetbrains.com/plugin/12014-intellivue/edit/versions/stable/541303

这被释放了。如果问题已解决，请告诉我，以便我可以关闭此问题。

**Comment by yebei199** [comment]
> This was released. Please let me know if issue is fixed so I can close this.
> 
> https://plugins.jetbrains.com/plugin/12014-intellivue/edit/versions/stable/541303
> 
> 这被释放了。如果问题已解决，请告诉我，以便我可以关闭此问题。

找到了, 在工具栏顶部, 和其他插件不一样, 不过可以用了

**Comment by Flamenco** [comment]
@yebei199 请发布屏幕截图，以便我看看它有何不同
