### ISSUE TITLE
Stop phoning home when usage reporting is disabled

### ISSUE THREAD

**Issue by hackel** [Flamenco/intellivue#4]
Whenever I start IDEA with the plugin enabled, it tries to connect to www.twelvetone.tv, even though I have disabled "Report Usage Anonymously".  This is entirely unacceptable.

Just release the source code so people can see exactly what you are doing for themselves.

**Comment by Flamenco** [comment]
Hi Ryan,

The RC version is not fully implemented. It currently sends exception reports and action counts to us help us focus our development.  We expect to release the official version in Q1 2020 to have the _disable option_ implemented, and at that time **we will remove the notices in the settings that mention that the options are not implemented**.

The current version of IntelliVue (RC15) actually has the mentioned options physically disabled.  I will mention at our next standup that you commented to make this even more clear. 

In the meantime, If you would like to use the plugin and do not want to wait for the final release, feel free to block the connection via other means; The plugin should still work.  If you have concerns about the submitted content, the data is sent in plain-text. 

In regards to source code, although free, this is a commercial product; Publishing the source code is not feasible at this time.  The _Creative Commons_ license is detailed in on the JetBrains site.  JetBrains also publishes the plugin under the 'No Source Code Available' category.

I will leave this issue open until we implement the *Disable Reporting* options.

**Comment by Flamenco** [comment]
@hackel We have released 1.0.0-FINAL and this issue has been addressed.  After reviewing the latest release, please confirm that your concerns have been addressed.
