### ISSUE TITLE
IntelliVue doesn't work with PHPStorm due to java plugin dependency

### ISSUE THREAD

**Issue by lllopo** [Flamenco/intellivue#7]
Latest IntelliVue does not work with PHPStorm as it lacks the Java plugin. Plugin fails with error :

`The IntelliVue (id=tv.twelvetone.intellij.plugins.intellivue, path=~\AppData\Roaming\JetBrains\PhpStorm2020.1\plugins\IntelliVuePlugin.jar, version=1.0.1) plugin requires "com.intellij.modules.java" plugin to be installed.`

**Comment by Flamenco** [comment]
Thank you for reporting the issue.

Did it work previously?

**Comment by lllopo** [comment]
Yes, it was working, but to be honest I did an update to the latest production PHPStorm and then soon after to the latest EAP, so I can't tell when it stopped exactly.

Edit: But also updated IntelliVue and I did it manually. It refused to update to the latest 1.0.1 on the PHPStorm EAP. The update process passed, then on restart of PHPStorm it reported the old version still. I did this twice and since the result was the same, I then downloaded the plugin and updated manually, which worked. 

My guess is - I see Jetbrains changed something in the requirements about the plugins manifests and more or less you were forced to add the com.intellij.modules.java as dependency in 1.0.x (at least that is what I see as complaints from a few other plugin developers). The problem is that this plugin comes only with IDEA, not with PHPStorm. So, I'm not sure how easy (and if at all) this can be fixed. If it is not fixable - that would be very unpleasant and unfortunate.

**Comment by Flamenco** [comment]
I can remove the Java library from my runtime and see where the dependency is, and if possible I will remove it.  The plugin's manifest does not declare a dependency to anything but vue and javascript.

**Comment by Flamenco** [comment]
We have another release that we will be posting that was built with the EAP, so that might just fix the issue as well.

**Comment by Flamenco** [comment]
Actually, as of 1.0.1 we declare a Java dependency, so that would make it not compatible.  I will still check to see why we need the Java plugin.

**Comment by plweil** [comment]
I've installed v.1.0.0 rc.18 with PHPStorm 2020.1, and I can't get any of the plugin stuff to work. Where would the Vue menu even appear if it was there?

**Comment by kelsos** [comment]
@plweil usually it is in the project view in when you use the new dialog in a folder. It should be below the second separator.

v1.0.0 rc.18 seems to be the latest version that works without problems with the other JetBrains IDEs. (I am using WebStorm)

**Comment by Flamenco** [comment]
As of IntelliJ version 2020.2, we were able to remove the dependency to Java.  So this now works in Webstorm.  Our new published version will be v1.1.0.

https://www.jetbrains.com/webstorm/nextversion/

<img width="484" alt="Screen Shot 2020-07-13 at 3 26 03 PM" src="https://user-images.githubusercontent.com/819940/87347619-812ca200-c521-11ea-9670-6596635bba75.png">

<img width="1291" alt="Screen Shot 2020-07-13 at 3 58 28 PM" src="https://user-images.githubusercontent.com/819940/87347880-e54f6600-c521-11ea-9c6b-98ff94768628.png">

**Comment by kelsos** [comment]
Awesome, thank you very much :)

**Comment by Flamenco** [comment]
They replaced JavaFX (the embedded HTML renderer) with and embedded version of Chrome.  That is going to open a bunch of feature possibilities, like previewing and debugging your component directly inside IJ.
