### ISSUE TITLE
Support for vue-i18n in SFC

### ISSUE THREAD

**Issue by killwort** [Flamenco/intellivue#8]
There's a popular localisation library usable with VUE https://kazupon.github.io/vue-i18n/
It would be great to have at least minimal support for it: a section in SFC analyser for <i18n>.
And it would be even better if code completion would support $t/$tc functions and check if their arguments really exist inside <i18n> dictionaries.

**Comment by kelsos** [comment]
@killwort I had the same problem and recently found out that there is actually a plugin for i18n that also supports `vue-i18n` that you can use along with intellivue.

**Comment by Flamenco** [comment]
Hi @killwort and @kelsos.  Thanks for your suggestion.

We use an inhouse localisation solution.  Our product actually solves many issues we have encountered.

1. Pulls down translations automatically in 100s of languages.
2. Searches, and gives us a report of what needs to be translated.
3. Lets us define what tags and elements translation text appears in.
4. Replaces selected text with templates or functions and creates stubs in translation files.
5. Auto creates translation files.
6. Provides report of what needs to be translated. 
7. Lets us refactor translation ids.
8. Finds and removes unused translations

Having said that, it is not likely we will focus our efforts on integrating a 3rd party product into IntelliVue. We have not released our in-house solution to the public yet, but may be if the interest is out there.

http://www.twelvetone.tv/docs/developer-tools/intellij-plugins/i18n

<img width="447" alt="Screen Shot 2020-07-12 at 11 08 55 AM" src="https://user-images.githubusercontent.com/819940/87250371-531c6480-c432-11ea-8952-eecdaf7e595b.png">
<img width="1758" alt="Screen Shot 2020-07-12 at 11 21 44 AM" src="https://user-images.githubusercontent.com/819940/87250372-54e62800-c432-11ea-8532-bc93512423e8.png">
<img width="1774" alt="Screen Shot 2020-07-12 at 11 22 02 AM" src="https://user-images.githubusercontent.com/819940/87250373-557ebe80-c432-11ea-9a4f-d9e60642b33b.png">
